version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - code:/code
      - static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    - "DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}"
    - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"

  db:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"